server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
#minio配置
minio:
  endpoint: http://localhost:9001               # minio 的url
  accessKey: minio                              # userName
  secretKey: minio@123456                       # password
  bucketName: demo

avatar: "https://n.sinaimg.cn/sinakd10109/410/w868h1142/20200824/3045-iyaiihm5428976.jpg"